### ISSUE TITLE
Error Timed out trying to establish connection

### ISSUE THREAD

**Issue by bardware** [sylvainlaurent/JDBC-Performance-Logger#64]
Hi,

I finally found the time to come back to your tool. I took the `0.8.2` release as available on `mvnrepository.com`. I end up with a new exception.

My working JDBC URL looks like `jdbc:macromedia:sqlserver://server:1433;databaseName=db`. I use driver `macromedia.jdbc.MacromediaDriver`.
What does not work is URL `jdbcperflogger:jdbc:macromedia:sqlserver://server:1433;databaseName=db` using driver `ch.sla.jdbcperflogger.driver.WrappingDriver`.
I have a configuration file that includes the following mapping:
```
    <jdbc-driver>
      <prefix>jdbc:macromedia:sqlserver:</prefix>
      <driver-class-name>macromedia.jdbc.MacromediaDriver</driver-class-name>
    </jdbc-driver>
```
When I provide a wrong password I get an authorization error. This looks like the communication to the database can be established. I wonder why does the JDBCPool throw the exception `Timed out ...`.
Is there some logging that makes information available what data is passed through your agent?

```
"Error","ajp-nio-8016-exec-6","12/23/17","20:30:20","","Timed out trying to establish connection"
java.sql.SQLException: Timed out trying to establish connection
	at coldfusion.server.j2ee.sql.pool.JDBCPool.requestConnection(JDBCPool.java:895)
	at coldfusion.server.j2ee.sql.pool.JDBCManager.requestConnection(JDBCManager.java:125)
	at coldfusion.server.j2ee.sql.JRunDataSource.getConnection(JRunDataSource.java:137)
	at coldfusion.sql.CFDataSource.getConnection(CFDataSource.java:44)
	at coldfusion.sql.Executive.verifyDatasource(Executive.java:552)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at coldfusion.runtime.StructBean.invoke(StructBean.java:508)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3166)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3074)
	at cfudflibrary2ecfm2142836872$funcVERIFYDSN.runFunction(/CFIDE/administrator/datasources/udflibrary.cfm:14)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:492)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:388)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:339)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:538)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3483)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:3464)
	at cfindex2ecfm1146061361._factor12(/CFIDE/administrator/datasources/index.cfm:450)
	at cfindex2ecfm1146061361._factor17(/CFIDE/administrator/datasources/index.cfm:396)
	at cfindex2ecfm1146061361._factor18(/CFIDE/administrator/datasources/index.cfm:168)
	at cfindex2ecfm1146061361.runPage(/CFIDE/administrator/datasources/index.cfm:1)
	at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:253)
	at coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:737)
	at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:573)
	at coldfusion.filter.CfincludeFilter.invoke(CfincludeFilter.java:65)
	at coldfusion.filter.IpFilter.invoke(IpFilter.java:45)
	at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:505)
	at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)
	at coldfusion.filter.PathFilter.invoke(PathFilter.java:153)
	at coldfusion.filter.LicenseFilter.invoke(LicenseFilter.java:30)
	at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94)
	at coldfusion.filter.BrowserDebugFilter.invoke(BrowserDebugFilter.java:78)
	at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
	at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)
	at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:60)
	at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
	at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
	at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)
	at coldfusion.CfmServlet.service(CfmServlet.java:219)
	at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42)
	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at coldfusion.inspect.weinre.MobileDeviceDomInspectionFilter.doFilter(MobileDeviceDomInspectionFilter.java:121)
	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at coldfusion.filter.ClickjackingProtectionFilter.doFilter(ClickjackingProtectionFilter.java:75)
	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:363)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:507)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by sylvainlaurent** [comment]
if you could run your java process with a debugger and set a breakpoint on java.sql.SQLException, then you could inspect the parameters of the call to coldfusion.server.j2ee.sql.pool.JDBCPool.requestConnection or maybe some instance variables in this method. That would give some indications on what could be wrong.
I don't use coldfusion, so I can help you only by giving some clues on how to track the problem...

**Comment by sylvainlaurent** [comment]
no activity, closing issue
