### ISSUE TITLE
properly stop threads and sockets

### ISSUE THREAD

**Issue by madness-inc** [sylvainlaurent/JDBC-Performance-Logger#66]
As stated here
https://github.com/sylvainlaurent/JDBC-Performance-Logger/blob/master/jdbc-perf-logger-driver/src/main/java/ch/sla/jdbcperflogger/driver/WrappingDriver.java#L72

`WrappingDriver.unload()` must properly shutdown the threads and sockets.

This leads to an error when used inside a web-application that is being restarted:

> java.lang.RuntimeException: java.net.BindException: Die Adresse wird bereits verwendet (Bind failed)
> 	at ch.sla.jdbcperflogger.logger.PerfLoggerServerThread.<init>(PerfLoggerServerThread.java:59)
> 	at ch.sla.jdbcperflogger.logger.PerfLoggerServerThread.<init>(PerfLoggerServerThread.java:26)
> 	at ch.sla.jdbcperflogger.logger.PerfLoggerServerThread$1.run(PerfLoggerServerThread.java:42)
> 	at ch.sla.jdbcperflogger.logger.PerfLoggerServerThread$1.run(PerfLoggerServerThread.java:35)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at ch.sla.jdbcperflogger.logger.PerfLoggerServerThread.spawn(PerfLoggerServerThread.java:35)
> 	at ch.sla.jdbcperflogger.logger.PerfLoggerRemoting.<clinit>(PerfLoggerRemoting.java:38)

**Comment by madness-inc** [comment]
Would a PR be welcome here?

**Comment by sylvainlaurent** [comment]
of course
